"""added cascade on author

Revision ID: ad6f4308cbaf
Revises: f170ce064daf
Create Date: 2023-08-07 00:00:24.262407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6f4308cbaf'
down_revision = 'f170ce064daf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'books', comment='cascade=True')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
