"""Date on date_of_birth

Revision ID: f170ce064daf
Revises: 48b134f71409
Create Date: 2023-08-06 23:27:45.589421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f170ce064daf'
down_revision = '48b134f71409'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
